#!/bin/sh

[ "${ACTION}" = "released" ] || exit 0

. /lib/functions.sh

logger "$BUTTON pressed for $SEEN HZ(100)"

if [ "$SEEN" -gt 500 ]
then
	echo "FACTORY RESET" > /dev/console
	jffs2reset -y && reboot &
fi

return 0
