#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=50

USE_PROCD=1
PROG=/usr/sbin/crond

validate_cron_section() {
	uci_validate_section system system "${1}" \
		'cronloglevel:uinteger'
}

start_service () {
	#0   3 * * * /sbin/reboot
	#*/5 * * * * /bin/pidof net4g || /bin/net4g -d
	[ ! -e "/etc/crontabs/root" ] && {
		cat > /etc/crontabs/root <<"EOF"
*/3 * * * * pidof mediasvr || /bin/mediasvr &
*/5 * * * * [ -e "/dev/ttyUSB2" ] && /sbin/ltepower.sh "/dev/ttyUSB2"
EOF
	}
	
	loglevel=$(uci_get "system.@system[0].cronloglevel")

	[ -z "${loglevel}" ] || {
		/sbin/validate_data uinteger "${loglevel}" 2>/dev/null
		[ "$?" -eq 0 ] || {
			echo "validation failed"
			return 1
		}
	}

	mkdir -p /var/spool/cron
	ln -s /etc/crontabs /var/spool/cron/ 2>/dev/null

	procd_open_instance
	procd_set_param command "$PROG" -f -c /etc/crontabs -l ${loglevel:-5}
	procd_close_instance
}

service_triggers()
{
	procd_add_validation validate_cron_section
}
