#!/bin/sh
PPP_IPPARAM="$6"

. /lib/netifd/netifd-proto.sh

rm -f /tmp/dialok
echo "$(date)- ppp down ###" >> /tmp/at_failed_ret

echo none > /sys/class/leds/regstat/trigger
echo 1 > /sys/class/leds/regstat/brightness

echo none > /sys/class/leds/dialstatus/trigger
echo 1 > /sys/class/leds/dialstatus/brightness

proto_init_update "$IFNAME" 0
proto_send_update "$PPP_IPPARAM"

[ -d /etc/ppp/ip-down.d ] && {
	for SCRIPT in /etc/ppp/ip-down.d/*
	do
		[ -x "$SCRIPT" ] && "$SCRIPT" "$@"
	done
}
